### ISSUE TITLE
Ready img file username and password are not mentioned

### ISSUE THREAD

**Issue by keshvari** [CIRCL/Circlean#55]
Hi 
I install ready image of the project and it worked for me.I want to consider the code but I can not login to raspberry because I don't know the username and password.I don't know from what point I should consider the project.If it is possible to guide me give me some clue which point I should start because I want to contribute to this project.

**Comment by Rafiot** [comment]
Hi,

The default image doesn't have any user you can use to login in order to avoid seeing an attacker compromising the raspberry pi that way.

If you want to contribute to the project, you have a few options:
* contributing to [PyCIRCLean](https://github.com/CIRCL/PyCIRCLean) (this is the core lib used in  CIRCLean)
* If there any changes you want to make to the bash scripts from circlean, you can plug the SD card in your computer (or mount the img file directly) and modify the files there.
